#! /bin/sh
case "$1" in
start)
echo "Starting init.d script and loading selected modules"
start-stop-daemon -S -n init -a /bin/scull_load
start-stop-daemon -S -n init -a /bin/module_load -- hello
start-stop-daemon -S -n init -a /bin/module_load -- faulty
;;
stop)
echo "Removing loaded modules"
start-stop-daemon -K -n scull_load
start-stop-daemon -K -n module_load
start-stop-daemon -S -n init -a /bin/scull_unload
start-stop-daemon -S -n init -a /bin/module_unload -- hello
start-stop-daemon -S -n init -a /bin/module_unload -- faulty
;;
*)
exit 1
esac
exit 0