#! /bin/sh
case "$1" in
start)
echo "Starting init.d TESTINGscript and loading selected modules"
echo $PWD
start-stop-daemon -S -n init -a /bin/scull_load -- scull
start-stop-daemon -S -n init -a /bin/module_load -- hello
start-stop-daemon -S -n init -a /bin/module_load -- faulty
start-stop-daemon -S -n init -a /bin/aesdchar_load 

;;
stop)
echo "Removing loaded modules"
start-stop-daemon -K -n scull_load
start-stop-daemon -K -n module_load
start-stop-daemon -S -n aesdchar_load
start-stop-daemon -S -n init -a /bin/scull_unload  -- scull
start-stop-daemon -S -n init -a /bin/module_unload -- hello
start-stop-daemon -S -n init -a /bin/module_unload -- faulty
start-stop-daemon -S -n init -a /bin/aesdchar_unload
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0